name: Generate Assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1. Generate the Snake
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: karxoo
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23cc7a67&color_dots=%23e5e7eb,%23d4b483,%23c1666b,%23435058,%2348392a
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23cc7a67&color_dots=%231c1c1c,%23d4b483,%23c1666b,%23435058,%2348392a

      # 2. Generate the Streak Stats
      - name: Generate Streak SVG
        uses: jaywcjlove/github-readme-streak-stats@main
        with:
          user: karxoo
          theme: catppuccin_mocha
          hide_border: true
          background: 1e1e2e
          output: dist/streak-stats.svg

      # 3. Generate Main GitHub Stats
      - name: Generate Main Stats SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=karxoo&show_icons=true&theme=catppuccin_mocha&hide_border=true
          path: dist/github-stats.svg
          token: ${{ secrets.GH_TOKEN }} # Using the PAT you created

      # 4. Generate Top Languages
      - name: Generate Top Langs SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=karxoo&layout=compact&theme=catppuccin_mocha&hide_border=true&langs_count=5
          path: dist/top-langs.svg
          token: ${{ secrets.GH_TOKEN }} # Using the PAT you created
          
      # 5. Push EVERYTHING to the 'output' branch
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
